# -*- coding: utf-8 -*-
"""new Font_text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18vQVFcZThI7kfcKW2jgRm_eWZ6g3dL7o
"""

import transformers

import torch

from transformers import GPT2LMHeadModel, GPT2Tokenizer
from IPython.display import display, HTML

model_name = 'gpt2'
tokenizer = GPT2Tokenizer.from_pretrained(model_name)
model = GPT2LMHeadModel.from_pretrained(model_name)

def generate_text(prompt, max_words):
    max_length = max_words * 2
    inputs = tokenizer.encode(prompt, return_tensors='pt')
    outputs = model.generate(
        inputs,
        max_length=max_length,
        num_return_sequences=1,
        temperature=0.7,
        top_k=50,
        top_p=0.95,
        no_repeat_ngram_size=2,
        do_sample=True
    )
    text = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return ' '.join(text.split()[:max_words])

# User input for topic and number of words
topic = input("Enter the topic: ")
num_words = int(input("Enter the number of words: "))

generated_paragraph = generate_text(f"Write a paragraph about {topic}.", num_words)

# HTML content with styled fonts
html_content = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Generated Text with Google Fonts</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Open+Sans&display=swap">
    <style>
        body {{ font-family: 'Brush Script MT', cursive; }}
        h1 {{ font-size: 2em; }}
        p {{ font-family: 'Brush Script MT', cursive; font-size: 1.5em; }}
        .serif {{ font-family: 'Garamond', serif; }}
    </style>
</head>
<body>
    <h1>Font 1 - Brush Script MT</h1>
    <p>{generated_paragraph}</p>
    <h1>Font 2 - Garamond</h1>
    <p class="serif">{generated_paragraph}</p>
</body>
</html>
"""

display(HTML(html_content))

